### PR TITLE
Update dialogs.dart

### PR DESCRIPTION
**Pull request by laminr**
removing ! to WidgetsBinding.instance

### CODE REVIEW

**Comment by zulfahmi93** [comment]
This change will cause the package to be incompatible with the users who haven't upgraded their SDK to Flutter 3.

**Comment by laminr** [comment]
can't you release it under a new version?

**Comment by laminr** [comment]
I have updated to +4. 
is that what was needed?

**Comment by zulfahmi93** [comment]
Since this is a public API change introduced with the Flutter 3 SDK, we need to:
1. Update the versioning from `0.1.0` to `0.2.0`. Since the `pub` client uses semantic versioning, the existing users using version `0.1.0` of this package should not be upgraded automatically to version `0.2.0`.
2. Update the Dart SDK constraint from `2.12.0` to `2.17.0`.
3. Update the Flutter SDK constraint from `2.0.0` to `3.0.0`.
4. Update the `README.md`'s _Building From Source_ section to reflect the new SDK constraints changes.

You can refer to the latest [commit](https://github.com/zulfahmi93/month-year-picker/commit/3ea4ad68061cd3d0d4dcad8014e1cc05dcfa2daa) that I've pushed.

I'll close your PR for now. Thanks for the contribution!

**Pull request closed without merging**
